[package]
name = "shulkerscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["zip", "lua"]
lang-debug = []
lua = ["shulkerscript-lang/lua"]
zip = ["shulkerbox/zip"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.12"
shulkerscript-lang = {path = "../shulkerscript-lang", features = ["shulkerbox"], default-features = false}
shulkerbox = {path = "../shulkerbox", default-features = false}

