[package]
name = "shulkerscript"
version = "0.1.0"
edition = "2021"

authors = ["Moritz Hölting <moritz@hoelting.dev>"]
categories = ["command-line-utilities", "compilers"]
description = "Command line tool to compile ShulkerScript projects"
repository = "https://github.com/moritz-hoelting/shulkerscript-cli"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["zip", "lua"]
lang-debug = []
lua = ["shulkerscript-lang/lua"]
zip = ["shulkerbox/zip"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.12"
shulkerscript-lang = { git = "https://github.com/moritz-hoelting/shulkerscript-lang", features = ["shulkerbox"], default-features = false, rev = "09b389c2060e73f686d92df3c45290c2c1b34ecb"}
shulkerbox = { git = "https://github.com/moritz-hoelting/shulkerbox", default-features = false, rev = "296502dcc5dd29b3d930ffec91ceec3d161e0e47" }
git2 = { version = "0.18.3", default-features = false }
path-absolutize = "3.1.1"
color-eyre = "0.6.3"

