[package]
name = "shulkerscript-cli"
version = "0.1.0"
edition = "2021"

authors = ["Moritz Hölting <moritz@hoelting.dev>"]
categories = ["command-line-utilities", "compilers"]
description = "Command line tool to compile ShulkerScript projects"
repository = "https://github.com/moritz-hoelting/shulkerscript-cli"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shulkerscript"
path = "src/main.rs"

[features]
default = ["zip", "lua", "watch"]
lang-debug = []
lua = ["shulkerscript/lua"]
watch = ["dep:notify-debouncer-mini", "dep:ctrlc"]
zip = ["shulkerbox/zip"]

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
colored = "2.1.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.12"
shulkerscript = { git = "https://github.com/moritz-hoelting/shulkerscript-lang", features = ["shulkerbox"], default-features = false, rev = "5336ffb91ed5dfa1b2fce3993d84a2876aa732a3" }
shulkerbox = { git = "https://github.com/moritz-hoelting/shulkerbox", default-features = false, rev = "b79c9ecd6d45f9319c9083a8103ef0186839b0c0" }
git2 = { version = "0.18.3", default-features = false }
path-absolutize = "3.1.1"
color-eyre = "0.6.3"
dotenvy = "0.15.7"
notify-debouncer-mini = { version = "0.4.1", default-features = false, optional = true }
ctrlc = { version = "3.4.4", optional = true }
